# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
    build:
        docker:
            - image: circleci/node:9.4
        working_directory: ~/repo
        steps:
            - checkout

            # Download the Firebase deployment keys
            - run: git clone git@bitbucket.org:cool-homeworks/ch-deploy-secrets.git

            # Download and cache dependencies
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package.json" }}
                      # fallback to using the latest cache if no exact match is found
                      - v1-dependencies-

            - run: yarn install && cd ./functions && npm install

            - save_cache:
                  paths:
                      - node_modules
                      - functions/node_modules
                  key: v1-dependencies-{{ checksum "package.json" }}

            # Build
            - run: REACT_APP_ENV=staging npm run build

            - persist_to_workspace:
                  root: .
                  paths:
                      - build
    deploy:
        docker:
            - image: circleci/node:9.4
        working_directory: ~/repo
        steps:
            - checkout
            - attach_workspace:
                  at: .
            - run: ./deploy.staging.sh

workflows:
    version: 2
    build_and_deploy:
        jobs:
            - build
            - approve:
                  type: approval
                  requires:
                      - build
            - deploy:
                  requires:
                      - approve
